#APP_NAME
spring:
  application:
    name: product-service

#DATABASE
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test_mem005
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.format_sql: false
  h2:
    console:
      enabled: true
      path: /h2-console

#PORT
server:
  port: 8080

#LOGGER
logging:
    level:
      root: warn
      org:
        springframework:
          web: debug
        hibernate: INFO
